### ISSUE TITLE
Optional opts parameter is not defined as optional

### ISSUE THREAD

**Issue by emadgit** [talon-one/talon_one.js#21]
Hey guys, happy new year  🥳 

I noticed in your latest version for your JavaScript SDK you start adding the Typescript definitions, which is awesome 🎉  as we also using Typescript in our side. I find something which you might want to take a look as it might be a type issue. 

As you can see [here](https://github.com/talon-one/talon_one.js/blob/de25225be5267e1a01a4aca601ba95059f39c4c2/dist/api/IntegrationApi.d.ts#L279) ( and other places where `opts` is defined ) it meant to be an optional parameter ( Based on the comments you have there ), but it's not defined as optional. I think you probably need to use `?` like  `opts?` to make it optional, otherwise it will be a mandatory parameter.

**Comment by fmoeckel** [comment]
Hello @emadgit.

Thank you very much for your suggestion. We are currently checking how much effort will be needed in order to change it accordingly. How critical is this for you?

**Comment by emadgit** [comment]
Hey @fmoeckel, 

Thanks for the response, currently we are live with an older sdk version which have no type definitions and we typed it in our side for the most parts, so the issue is not hitting us at the moment, but if we going to upgrade to the latest version we will face to some issues, which I hope you can resolve it by then :)

**Comment by altJake** [comment]
Hey @emadgit,

Sorry it took us so long to make ends meet. It was harder than one might assume to be honest, and it's still not perfect.

Thank you very much for using the SDK and reporting the issue!

#22 should introduce most type functionality around optional parameters, and for the rest we are already working on a patch for the [OpenAPI Generator](https://github.com/OpenAPITools/openapi-generator).

Stay tuned to the PR, the version is in final testing stages and we will probably release `v4.3.0` by the end of this week 🎉
