### ISSUE TITLE
What is the default behaviour in getCouponsByAttributesApplicationWide options?

### ISSUE THREAD

**Issue by Kraloz** [talon-one/talon_one.js#24]
I was reading the docs and I didn't can find anything related to the default behaviour of the options in this request:
(notice that I did comment multiple request options)
```ts
    const apiInstance = new TalonOne.ManagementApi();
    const applicationId = environment.TALON_APP_ID;
    const body = new TalonOne.CouponSearch({});
    const opts = {
      value:                  couponName,
      // valid:                  'expired', // 'validFuture' 'validNow',
      // usable:                 'usable_example',
     // campaignState:          'enabled' // String | Filter results by the state of the campaign.
    };
    const apiResponse = await apiInstance.getCouponsByAttributesApplicationWide(applicationId, body, opts as any);
```

For example, if I don't specify the `valid` or the `usable` option what should I expect?

**Comment by altJake** [comment]
Hi @Kraloz 

Firstly I want to thank you for your question and to apologize for the delay in my response.

The coupon searching endpoints allow searching for coupons according to different criterias and options.
 As you already pointed out, excluding some of the optional query parameters will affect the response from the endpoint, however, those options are mainly useful when one does not know the exact value of the coupon to search for. For examples:
 > Find all **valid** coupons, that were **created after** May, 1st, 2021

 Would look as follows in code:
 ```js
 const apiInstance = new TalonOne.ManagementApi();
const applicationId = environment.TALON_APP_ID;
const body = new TalonOne.CouponSearch({});
const opts = {
  valid:  'validNow',
  createdAfter: '2021-05-01 00:00:00'
};
const apiResponse = await apiInstance.getCouponsByAttributesApplicationWide(applicationId, body, opts as any);
```

However, looking at the code snippet you shared, I could notice that you are looking for a specific coupon with a **known value**, which makes me believe that, as you already figured out, the rest of restrictions are redundant for that case.
So to answer your last question, you should expect the coupon with that value to be returned, independent of whether it is valid, usable or the state of the campaign it is in.

As a rule of thumb, query parameter options, when provided, are **adding a restriction(s)** to the returned response, filtering out coupons that do not comply to the requested options. i.e. request with `valid: "validFuture"` alone, will only return coupons that are _not yet valid_ in the provided application.

I hope that answers you questions and if not, please feel free to follow-up here, I would be happy to provide any help needed.

P.S.
I can imagine that you were looking our developer docs up, and I would like to share with you our _new_ developers website, which will be published very soon and we believe will be much more user and developer friendly: https://docs.talon.one/
